<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GEJUD-536163" name="Default test" tests="3" failures="1" timestamp="9 May 2016 20:56:35 GMT" time="25.722" errors="0">
  <testcase name="mTestaProcessoRotinaDeIncluirUmNovoProcesso" time="21.876" classname="tjmg.pje.Integracao.RegraDeNegocio.JUnit.ClsTestaOpcaoDoMenuProcesso">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at tjmg.pje.Interface.Usuario.WebDriver.ClsPaginaInclusaoDeUmProcesso.BotaoMenuIncluirProcesso(ClsPaginaInclusaoDeUmProcesso.java:27)
	at tjmg.pje.Integracao.RegraDeNegocio.JUnit.ClsTestaOpcaoDoMenuProcesso.mTestaProcessoRotinaDeIncluirUmNovoProcesso(ClsTestaOpcaoDoMenuProcesso.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </failure>
  </testcase> <!-- mTestaProcessoRotinaDeIncluirUmNovoProcesso -->
  <testcase name="mTestaProcessoRotinaDeIncluirUmNovoProcessoIncidental" time="0.001" classname="tjmg.pje.Integracao.RegraDeNegocio.JUnit.ClsTestaOpcaoDoMenuProcesso"/>
  <testcase name="mTestaProcessoRotinaDeProcessoNaoProtocolado" time="0.001" classname="tjmg.pje.Integracao.RegraDeNegocio.JUnit.ClsTestaOpcaoDoMenuProcesso"/>
</testsuite> <!-- Default test -->
